# Generated by Django 4.0.1 on 2022-01-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='data',
            field=models.DateField(null=True, verbose_name='2022-01-20'),
        ),
    ]
