# Generated by Django 4.0.1 on 2022-01-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='data',
        ),
    ]
