# Generated by Django 4.0.1 on 2022-01-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='store',
            field=models.CharField(default='12.12.21', max_length=500),
            preserve_default=False,
        ),
    ]
